[WIP] Run Chip Tool without sudo
canonical/chip-tool-snap pull request #55
Opened 2024-05-02 08:41 UTC by jpm-canonical

We had to use sudo because of the directory where Chip Tool stores its config and data (Resolves #17). After an upstream changes we can set the `TMPDIR` env var to tell Chip Tool where to store its data.

This PR tries to:
* Set `TMPDIR` to snap home dir (`SNAP_USER_COMMON`) using command chain
* Removed outdated path rewrites and unnecessary mounts

Testing is needed to see if this change is actually effective, and previous functionality is unchanged.

2024-05-02 08:49 UTC, jpm-canonical commented
Previously there was an issue where history is not persisted (#20).

Using this branch, running a few commands in interactive mode, we can see the history is now stored in `$SNAP_USER_COMMON`.

```
$ chip-tool interactive start
>>> onoff toggle 110 1
[1714638608.210295][285852:285852] CHIP:TOO: Command: onoff toggle 110 1
>>> quit
[1714638614.446034][285852:285852] CHIP:TOO: Command: quit 
[1714638614.446330][285852:285852] CHIP:TOO: Unknown cluster or command set: quit
>>> exit
[1714638616.938403][285852:285852] CHIP:TOO: Command: exit 
[1714638616.938520][285852:285852] CHIP:TOO: Unknown cluster or command set: exit
^C
$ cd /home/jpmeijers/snap/chip-tool/common
$ ls
chip_tool_config.alpha.ini  chip_tool_history
chip_tool_config.ini        chip_tool_kvs
$ cat chip_tool_history 
onoff toggle 110 1
quit
exit
```

2024-05-03 14:01 UTC, jpm-canonical commented
❌ If `chip-tool` was run with sudo, and you try to run it without sudo after that, it can't open the files in `/tmp`, as they are owned by root.

```
$ chip-tool pairing onnetwork 110 20202021
[1714744727.897352][25324:25324] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /home/jpmeijers/snap/chip-tool/common/chip_tool_kvs
[1714744727.897477][25324:25324] CHIP:DL: writing settings to file (/home/jpmeijers/snap/chip-tool/common/chip_tool_kvs-LoTsJE)
[1714744727.897558][25324:25324] CHIP:DL: renamed tmp file to file (/home/jpmeijers/snap/chip-tool/common/chip_tool_kvs)
[1714744727.897986][25324:25324] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1714744727.897996][25324:25324] CHIP:DL: ChipLinuxStorage::Init: Attempt to re-initialize with KVS config file: /tmp/chip_kvs
[1714744727.900503][25324:25324] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_factory.ini
[1714744727.900593][25324:25324] CHIP:DL: writing settings to file (/tmp/chip_factory.ini-qTVr56)
[1714744727.900640][25324:25324] CHIP:DL: failed to rename (/tmp/chip_factory.ini-qTVr56), Operation not permitted (1)
[1714744727.900659][25324:25324] CHIP:DL: Configuration Manager initialization failed: src/platform/Linux/CHIPLinuxStorageIni.cpp:116: CHIP Error 0x000000AF: Write to file failed
[1714744727.900669][25324:25324] CHIP:-: src/platform/Linux/CHIPLinuxStorageIni.cpp:116: CHIP Error 0x000000AF: Write to file failed at ../examples/chip-tool/commands/common/CHIPCommand.cpp:142
[1714744727.900679][25324:25324] CHIP:TOO: Run command failure: src/platform/Linux/CHIPLinuxStorageIni.cpp:116: CHIP Error 0x000000AF: Write to file failed
[1714744727.912484][25324:25324] CHIP:SPT: VerifyOrDie failure at src/system/SystemLayerImplSelect.h:59: mLayerState.Destroy()
Aborted (core dumped)
```

2024-06-12 15:55 UTC, farshidtz commented on tests/common.go
> +	return errors.New(fmt.Sprintf("snap '%s' not found", snapName))
Could use https://pkg.go.dev/github.com/canonical/matter-snap-testing@v1.0.0-beta.3/utils#SnapVersion?

2024-06-13 07:01 UTC, farshidtz requested changes
Thanks. It looks good apart from a few minor issues.

2024-06-13 07:01 UTC, farshidtz commented on tests/upgrade_test.go
> +		}
Use [`assert.NoError`](https://pkg.go.dev/github.com/stretchr/testify/assert#NoError) and pass a custom error message.

2024-06-13 11:45 UTC, jpm-canonical commented on tests/common.go
> +const allClusterSnap = "matter-all-clusters-app"
This typo was there originally. Let's fix it in a separate PR to keep this one's diff clean.

2024-06-13 11:56 UTC, jpm-canonical commented on tests/common.go
> +const allClusterSnap = "matter-all-clusters-app"
https://github.com/canonical/chip-tool-snap/issues/64

2024-06-13 14:48 UTC, farshidtz approved these changes
Great. Thanks a lot for the fix and adding tests.

2024-06-13 14:49 UTC, merged