Test configure radio URL
canonical/chip-tool-snap pull request #66
Opened 2024-06-18 15:48 UTC by jpm-canonical

## Summary

Solves #62

* Add configuration for the local and remote radio URLs
* Refactor constants out to a dedicated file

## Testing Steps

* Check if test is passing in github actions

2024-06-20 13:34 UTC, farshidtz requested changes
A few minor documentation issues.
Can't run the tests right now because snap store return 503.

2024-06-20 13:34 UTC, farshidtz commented on tests/README.md
> + LOCAL_INFRA_IF   | no       | wlan0                           | wlan0                             | Local backhaul network interface
```suggestion
 LOCAL_INFRA_IF   | no       | wlan0                           | Local backhaul network interface  
```

2024-06-20 13:34 UTC, farshidtz commented on tests/README.md
> + LOCAL_RADIO_URL  | no       | spinel+hdlc+uart:///dev/ttyACM0 | Local RCP serial port
```suggestion
 LOCAL_RADIO_URL  | no       | spinel+hdlc+uart:///dev/ttyACM0 | Local RCP URL             
```

2024-06-20 13:34 UTC, farshidtz commented on tests/README.md
> + REMOTE_RADIO_URL | no       | spinel+hdlc+uart:///dev/ttyACM0 | Remote RCP serial port
```suggestion
 REMOTE_RADIO_URL | no       | spinel+hdlc+uart:///dev/ttyACM0 | Remote RCP URL            
```

2024-06-20 15:26 UTC, jpm-canonical commented
This PR was used to test #67. Both generic and thread tests passed, using `/dev/ttyACM1` on local host.

2024-06-21 08:56 UTC, farshidtz approved these changes
I also just tested and it works as expected.

2024-06-21 09:18 UTC, farshidtz commented
Updated the PR title.

2024-06-21 09:18 UTC, merged